// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epoeuralzmwjxcwyvzro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwb2V1cmFsem13anhjd3l2enJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzE4NTYsImV4cCI6MjA2Mjg0Nzg1Nn0.ojDUIg4BaMBPCB2xwbUufWEHyx696dlMaxUmophkcqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);